name: Build libwhisper.so for Android

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    name: Build for Android (arm64-v8a)

    steps:
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Install Android NDK
        run: |
          sdkmanager --install "ndk;25.1.8937393"
          sdkmanager --install "cmake;3.22.1"

      - name: Checkout whisper.unity (your fork)
        uses: actions/checkout@v3
        with:
          path: whisper-unity

      - name: Checkout whisper.cpp
        uses: actions/checkout@v3
        with:
          repository: ggerganov/whisper.cpp
          ref: v1.7.5
          path: whisper-cpp

      - name: Build libwhisper.so
        run: |
          mkdir build-android
          cd build-android
          cmake ../whisper-cpp \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk/25.1.8937393/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-21 \
            -DBUILD_SHARED_LIBS=ON \
            -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release

      - name: Upload libwhisper.so
        uses: actions/upload-artifact@v4
        with:
          name: libwhisper-android
          path: |
            build-android/libwhisper.so
            build-android/**/*.so
          if-no-files-found: error
